### PR TITLE
to_string now encodes player 1 in blue and player 2 in green

### PR DESCRIPTION
**Pull request by qharlie**
Using simple asci terminal colors , should work on unixes and windows according to http://stackoverflow.com/questions/287871/print-in-terminal-with-colors-using-python

### CODE REVIEW

**Comment by qharlie** [comment]
Everyone loves screenshots http://imgur.com/a/uIKiT

**Comment by luiscosio** [comment]
Works great, thank you!

**Comment by cgearhart** [comment]
This is great! I didn't see it before I pushed breaking changes. Would you mind resolving the conflicts with the current version and then I'll merge?

**Comment by qharlie** [comment]
Sure np, I need to finish P3 first but will put this on the list.

**Comment by ianb** [comment]
I was doing something a little similar, but using Unicode: `symbols=['🔸', '🔹']`

**Pull request closed without merging**
